create table if not exists wrestling.ranking_sync_status (
  id bigint generated by default as identity primary key,
  source text not null default 'season_recalculation',
  last_synced_at timestamptz not null default now(),
  total_athletes_indexed bigint not null default 0,
  eligible_athletes_indexed bigint not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists ranking_sync_status_last_synced_idx
  on wrestling.ranking_sync_status (last_synced_at desc);
alter table wrestling.ranking_sync_status enable row level security;
grant select on wrestling.ranking_sync_status to anon, authenticated;
grant select, insert, update, delete on wrestling.ranking_sync_status to service_role;
drop policy if exists "Public can read ranking sync status" on wrestling.ranking_sync_status;
create policy "Public can read ranking sync status"
on wrestling.ranking_sync_status
for select
using (true);
create or replace function public.get_latest_ranking_status()
returns table (
  last_updated timestamptz,
  next_update timestamptz,
  total_athletes_indexed bigint,
  eligible_athletes_indexed bigint
)
language sql
stable
as $$
  select
    status.last_synced_at as last_updated,
    status.last_synced_at + interval '7 days' as next_update,
    status.total_athletes_indexed,
    status.eligible_athletes_indexed
  from wrestling.ranking_sync_status status
  order by status.last_synced_at desc
  limit 1;
$$;
grant execute on function public.get_latest_ranking_status() to anon, authenticated, service_role;
create table if not exists wrestling.profile_views (
  id uuid primary key default gen_random_uuid(),
  athlete_id uuid not null references wrestling.profiles(id) on delete cascade,
  viewer_user_id uuid not null references auth.users(id) on delete cascade,
  viewer_role text not null default 'recruiter',
  viewer_state text,
  created_at timestamptz not null default now()
);
create index if not exists profile_views_athlete_created_idx
  on wrestling.profile_views (athlete_id, created_at desc);
create index if not exists profile_views_viewer_athlete_created_idx
  on wrestling.profile_views (viewer_user_id, athlete_id, created_at desc);
alter table wrestling.profile_views enable row level security;
grant select, insert on wrestling.profile_views to authenticated;
grant select, insert, update, delete on wrestling.profile_views to service_role;
drop policy if exists "Recruiters can insert their own profile views" on wrestling.profile_views;
create policy "Recruiters can insert their own profile views"
on wrestling.profile_views
for insert
to authenticated
with check (auth.uid() = viewer_user_id);
drop policy if exists "Users can read relevant profile views" on wrestling.profile_views;
create policy "Users can read relevant profile views"
on wrestling.profile_views
for select
to authenticated
using (
  viewer_user_id = auth.uid()
  or exists (
    select 1
    from wrestling.profiles profile
    where profile.id = athlete_id
      and profile.user_id = auth.uid()
  )
);
create table if not exists wrestling.recruiter_nudges (
  id uuid primary key default gen_random_uuid(),
  athlete_id uuid not null references wrestling.profiles(id) on delete cascade,
  recruiter_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'requested',
  created_at timestamptz not null default now(),
  unique (athlete_id, recruiter_id)
);
create index if not exists recruiter_nudges_recruiter_created_idx
  on wrestling.recruiter_nudges (recruiter_id, created_at desc);
create index if not exists recruiter_nudges_athlete_created_idx
  on wrestling.recruiter_nudges (athlete_id, created_at desc);
alter table wrestling.recruiter_nudges enable row level security;
grant select, insert on wrestling.recruiter_nudges to authenticated;
grant select, insert, update, delete on wrestling.recruiter_nudges to service_role;
drop policy if exists "Recruiters can insert their own nudges" on wrestling.recruiter_nudges;
create policy "Recruiters can insert their own nudges"
on wrestling.recruiter_nudges
for insert
to authenticated
with check (auth.uid() = recruiter_id);
drop policy if exists "Users can read relevant recruiter nudges" on wrestling.recruiter_nudges;
create policy "Users can read relevant recruiter nudges"
on wrestling.recruiter_nudges
for select
to authenticated
using (
  recruiter_id = auth.uid()
  or exists (
    select 1
    from wrestling.profiles profile
    where profile.id = athlete_id
      and profile.user_id = auth.uid()
  )
);
create or replace view wrestling.trending_athletes as
with athlete_match_results as (
  select
    match.id,
    match.match_date,
    match.winner_id as athlete_id,
    true as is_win
  from wrestling.matches match
  union all
  select
    match.id,
    match.match_date,
    match.loser_id as athlete_id,
    false as is_win
  from wrestling.matches match
),
ordered_results as (
  select
    result.athlete_id,
    result.is_win,
    row_number() over (
      partition by result.athlete_id
      order by result.match_date desc, result.id desc
    ) as row_number
  from athlete_match_results result
),
streak_windows as (
  select
    ordered.athlete_id,
    ordered.is_win,
    ordered.row_number,
    min(case when not ordered.is_win then ordered.row_number end) over (
      partition by ordered.athlete_id
    ) as first_loss_row
  from ordered_results ordered
),
win_streaks as (
  select
    streak.athlete_id,
    coalesce(
      sum(
        case
          when streak.is_win
            and streak.row_number < coalesce(streak.first_loss_row, 2147483647)
          then 1
          else 0
        end
      ),
      0
    )::integer as recent_win_streak
  from streak_windows streak
  group by streak.athlete_id
),
profile_views_24h as (
  select
    view_log.athlete_id,
    count(*)::integer as views_last_24h
  from wrestling.profile_views view_log
  where view_log.created_at >= now() - interval '24 hours'
  group by view_log.athlete_id
)
select
  profile.id as athlete_id,
  profile.full_name,
  profile.state,
  profile.gender,
  profile.high_school_name,
  profile.club_name,
  profile.unified_score,
  profile.previous_rank,
  coalesce(streak.recent_win_streak, 0) as recent_win_streak,
  coalesce(view_count.views_last_24h, 0) as profile_views_24h,
  (
    coalesce(streak.recent_win_streak, 0) * 2
    + coalesce(view_count.views_last_24h, 0) * 1
  )::numeric(10, 2) as trend_score
from wrestling.profiles profile
left join win_streaks streak on streak.athlete_id = profile.id
left join profile_views_24h view_count on view_count.athlete_id = profile.id
where coalesce(profile.unified_score, 0) > 0;
grant select on wrestling.trending_athletes to anon, authenticated, service_role;
